spring:
  data:
    mongodb:
      database: produce_sync
      port: 27017
      host: localhost

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  config:
    file: gcp-account-file.json
  project:
    id: eighth-gamma-413101
  bucket:
    id: productsync_product

opencage:
  key: f374b40d10584d2e9381a6c51caebb0c
  url: https://api.opencagedata.com/geocode/v1/json
